---
#
# THAM KHAO https://phoenixnap.com/kb/how-to-install-docker-on-centos-8
#

- name: install a few prerequisite packages
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - yum-utils
    - ebtables
    - ethtool
    - curl

- name: app repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: upgrade all packages
  yum:
    name: '*'

- name: install Docker
  yum: name=docker-ce-3:19.03 state=latest

- name: executing the Docker Command Without Sudo (Optional)
  command: usermod -aG docker $(whoami)

- name: copy file daemon.json
  copy: src=templates/docker/daemon.json dest=/etc/docker

- name: start Docker
  service:
    name: docker
    state: started
