---
  # - import_tasks: node.yml
  # - import_tasks: nginx.yml
  - import_tasks: redis.yml
  # - import_tasks: ruby.yml
  # - import_tasks: postgres.yml
  # - import_tasks: user.yml
  # - import_tasks: docker.yml
  # - import_tasks: kube.yml
