---
- name: install lib for postgres
  yum: name={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - postgresql-server

- name: enable and start postgresql
  service:
    name: postgresql
    state: started

- name: create database
  become_user: postgres
  postgresql_db:
    name: "{{ pg_database_name }}"

- name: create user of database
  become_user: postgres
  postgresql_user:
    db: "{{ pg_database_name }}"
    name: "{{ pg_database_user }}"
    password: "{{ pg_database_pass }}"

- name: grant user for database
  become_user: postgres
  postgresql_privs:
    db: "{{ pg_database_name }}"
    state: present
    priv: ALL
    objs: ALL_IN_SCHEMA
    role: "{{ pg_database_user }}"
