---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install redis
  yum: name=redis state=latest

- name: start and enable redis
  service:
    name: redis
    state: started
