---
- name: create group {{ group }}
  group:
    name: "{{ group }}"
    state: present

- name: create user {{ owner }}
  user:
    name: "{{ owner }}"
    state: present
    shell:  /bin/bash

  # TODO: cannot create password for user
- name: update user password
  become: yes
  user:
    name: "{{ owner }}"
    password: "{{ password }}"

  # TODO: if you want to disable password
  # echo "app ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
- name: modify full permission user
  lineinfile: line='"{{ owner }}" ALL=(ALL:ALL) ALL' dest=/etc/sudoers

- name: create folder .ssh
  file: path="{{ working_dir }}/.ssh" state=directory

- name: setup ssh
  authorized_key:
    user: "{{ owner }}"
    state: present
    key: '{{ lookup("file", "{{ my_ssh }}/id_rsa.pub") }}'
    path: "{{ working_dir }}/.ssh/authorized_keys"

- name: create file bash_profile
  file:
    path: "{{ working_dir }}/.bash_profile"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0644
    state: touch

- name: setup .bash_profile
  blockinfile:
    dest: "{{ working_dir }}/.bash_profile"
    insertbefore: BOF
    block: |
      if [ -f ~/.bashrc ]; then
        . ~/.bashrc
      fi
